### ISSUE TITLE
[question] does thumpcord transmit chat from a single player world to a discord channel?

### ISSUE THREAD

**Issue by misterfixit** [Emberwalker/Thumpcord#5]
by that I mean most discord mods I have seen use a bot linked to the mc server that relays the chat, im looking for a mod that will relay chat from a single player world as well.

**Comment by skye-pp** [comment]
Yes, you just need to install Thump and Thumpcord locally then it should work from your single player world.

**Comment by Wyldern** [comment]
Yep - You'll still need to create a bot in Discord's developer site as normal to attach to, but Thumpcord works in single-player just fine; set it up as you would on the server and it should be fine. If not, let us know!
